spring:
  application:
    name: eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  # Optional Eureka server settings if using server
  # server:
  #   max-threads-for-peer-replication: 0
  # enable-self-preservation: false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId},%X{spanId}]"
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"


server:
  port: 8761  

# Optional commented properties (Zipkin, Sleuth, RabbitMQ)
#spring.sleuth.sampler.percentage: 1
#spring.zipkin.base-url: http://localhost:9411/
#spring.zipkin.sender.type: rabbit
#spring.zipkin.rabbitmq.queue: zipkin
#spring.rabbitmq.host: localhost
#spring.rabbitmq.port: 5672
#spring.rabbitmq.username: guest
#spring.rabbitmq.password: guest
