global:
  scrape_interval: 15s  # Scrape every 15 seconds

scrape_configs:
  - job_name: 'docker'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka-server:8761']  # Replace with the correct target services if they expose metrics on HTTP
  - job_name: 'elasticsearch'
    static_configs:
    - targets: ['elasticsearch-exporter:9114']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']
      
      
      
      
