## if same key present in global then iti is overirde by specific service key
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      path: /h2-console
      enabled: true

server:
  port: 8001

logging:
  file:
    name: "D:/Gaurav/Study/Programs/Backend Programs/microservice/microservice2/microservice_logs/exchange-service/application.log"
  pattern:
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  logstash:
    enabled: true
    destination: localhost:5004
    custom-fields: '{"service":"gateway-server"}'