spring:
  application:
    name: spring-cloud-config-server

  profiles:
    active: git   # or default

  cloud:
    config:
      server:
        git:
          uri: https://github.com/gauravk030/git-config-repo.git
          search-paths: config
          default-label: master
          clone-on-start: true

server:
  port: 8888
